version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: coffee_crm_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: coffee_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coffee_network

volumes:
  postgres_data:

networks:
  coffee_network:
    driver: bridge
